/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juandiaz
 */
public class AdminPanel extends javax.swing.JFrame {

    public DefaultTableModel ListaUser;
    public DefaultTableModel InvCantidadPrecio;
    public DefaultTableModel ArtEmpVencido;
    public DefaultTableModel RepVentPorFecha;
    public DefaultTableModel RepEmpPorFecha;
    public DefaultTableModel DatostablaListadoPawnVencida;
    static Boolean Access=false;

    public AdminPanel() {
        initComponents();
        GroupButton.add(NoOrdButton);
        GroupButton.add(OrdButton);
        Encabezado.setText(Encabezado.getText() + LoginPage.datoDeIngreso[0]);
        LecturaEscritura.ActualizarPawns("listadoEmpeñado.csv");

        //TABLA USUARIO
        ListaUser = new DefaultTableModel();
        ListaUser.addColumn("Primer nombre");
        ListaUser.addColumn("Segundo nombre");
        ListaUser.addColumn("Primer apellido");
        ListaUser.addColumn("Segundo apellido");
        ListaUser.addColumn("Cedula");
        ListaUser.addColumn("Contraseña");
        ListaUser.addColumn("Es Admin");
        LecturaEscritura.actualizarTabla("usuarios.csv", ListaUser, TablaUser);

        //TABLA DE INVENTARIO
        InvCantidadPrecio = new DefaultTableModel();
        InvCantidadPrecio.addColumn("Codigo");
        InvCantidadPrecio.addColumn("Artículo");
        InvCantidadPrecio.addColumn("Descripcion");
        InvCantidadPrecio.addColumn("Precio");
        InvCantidadPrecio.addColumn("Cantidad");
        InvCantidadPrecio.addColumn("NombreVendedor");
        InvCantidadPrecio.addColumn("CedulaVendedor");
        LecturaEscritura.actualizarTabla("listadoArticulo.csv", InvCantidadPrecio, TablaProd);

        //TABLA REPORTE DE VENTA POR FECHA
        RepVentPorFecha = new DefaultTableModel();
        RepVentPorFecha.addColumn("idProducto");
        RepVentPorFecha.addColumn("Fecha de venta");
        RepVentPorFecha.addColumn("Artículo");
        RepVentPorFecha.addColumn("Cantidad");
        RepVentPorFecha.addColumn("Precio Unitario");
        RepVentPorFecha.addColumn("Precio Total");
        RepVentPorFecha.addColumn("Comprador");
        RepVentPorFecha.addColumn("Cedula Comprador");
        RepVentPorFecha.addColumn("Vendedor");
        RepVentPorFecha.addColumn("Cedula Vendedor");
        LecturaEscritura.actualizarTabla("listadoDeCompra.csv", RepVentPorFecha, tablaReporteVenta);

        //TABLA REPORTE EMPEÑO
        RepEmpPorFecha = new DefaultTableModel();
        RepEmpPorFecha.addColumn("idEmpeño");
        RepEmpPorFecha.addColumn("Artículo");
        RepEmpPorFecha.addColumn("Descripción");
        RepEmpPorFecha.addColumn("Cantidad");
        RepEmpPorFecha.addColumn("PrecioUnitario");
        RepEmpPorFecha.addColumn("PrecioTotal");
        RepEmpPorFecha.addColumn("FechaInicial");
        RepEmpPorFecha.addColumn("FechaLimite");
        RepEmpPorFecha.addColumn("Empeñador");
        RepEmpPorFecha.addColumn("Cedula");
        LecturaEscritura.actualizarTabla("listadoEmpeñado.csv", RepEmpPorFecha, tablaReportePawn);

        //TABLA EMPEÑOS VENCIDO
        DatostablaListadoPawnVencida = new DefaultTableModel();
        DatostablaListadoPawnVencida.addColumn("idEmpeño");
        DatostablaListadoPawnVencida.addColumn("Artículo");
        DatostablaListadoPawnVencida.addColumn("Descripción");
        DatostablaListadoPawnVencida.addColumn("Cantidad");
        DatostablaListadoPawnVencida.addColumn("PrecioUnitario");
        DatostablaListadoPawnVencida.addColumn("PrecioTotal");
        DatostablaListadoPawnVencida.addColumn("FechaInicial");
        DatostablaListadoPawnVencida.addColumn("FechaLimite");
        DatostablaListadoPawnVencida.addColumn("Empeñador");
        DatostablaListadoPawnVencida.addColumn("Cedula");
        LecturaEscritura.actualizarTabla("listadoEmpeñadoVencido.csv", DatostablaListadoPawnVencida, tablaPawnVencida);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        GroupButton = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Encabezado = new javax.swing.JLabel();
        btnCerraSesion = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUser = new javax.swing.JTable();
        btnAbrirModalEditar = new javax.swing.JButton();
        btnActualizarUsuarios = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaProd = new javax.swing.JTable();
        btnAceptarFiltroCantidad = new javax.swing.JButton();
        NoOrdButton = new javax.swing.JRadioButton();
        OrdButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputValorMinSearch = new javax.swing.JTextField();
        inputValorMaxSearch = new javax.swing.JTextField();
        inputCantSearch = new javax.swing.JTextField();
        mensajeErrorFiltroCantidad = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaPawnVencida = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaReporteVenta = new javax.swing.JTable();
        btnSinFiltro1 = new javax.swing.JButton();
        btnFiltrarFecha1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputFechaInferio1 = new javax.swing.JTextField();
        inputFechaSuperior1 = new javax.swing.JTextField();
        mensajeErrorFecha1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaReportePawn = new javax.swing.JTable();
        btnSinFiltro2 = new javax.swing.JButton();
        btnFiltrarFecha2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        inputFechaInferio2 = new javax.swing.JTextField();
        inputFechaSuperior2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mensajeErrorFecha2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1032, 5));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        Encabezado.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Encabezado.setText("Saludos, ");

        btnCerraSesion.setText("Cerrar Sesión");
        btnCerraSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerraSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerraSesion)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCerraSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        TablaUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Primer nombre", "Segundo nombre", "Primer apellido", "Segundo apellido", "Cedula", "Contraseña", "Es Admin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaUser);

        btnAbrirModalEditar.setText("Editar");
        btnAbrirModalEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirModalEditarActionPerformed(evt);
            }
        });

        btnActualizarUsuarios.setText("Actualizar");
        btnActualizarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUsuariosActionPerformed(evt);
            }
        });

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnActualizarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAbrirModalEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbrirModalEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jTabbedPane1.addTab("Lista Usuarios", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Titulo", "Descripcion", "Precio", "Cantidad", "NombreVendedor", "CedulaVendedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TablaProd);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 1020, 390));

        btnAceptarFiltroCantidad.setText("Aceptar");
        btnAceptarFiltroCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarFiltroCantidadActionPerformed(evt);
            }
        });
        jPanel3.add(btnAceptarFiltroCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 218, 50));

        NoOrdButton.setText("Sin filtro");
        NoOrdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoOrdButtonActionPerformed(evt);
            }
        });
        jPanel3.add(NoOrdButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 106, -1));

        OrdButton.setText("Filtrar");
        OrdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdButtonActionPerformed(evt);
            }
        });
        jPanel3.add(OrdButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 80, -1));

        jLabel1.setText("Valor Minimo: ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));

        jLabel2.setText("Valor Maximo: ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        jLabel3.setText("Cantidad: ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, -1, -1));
        jPanel3.add(inputValorMinSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 100, 20));
        jPanel3.add(inputValorMaxSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 94, 20));
        jPanel3.add(inputCantSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 94, 20));

        mensajeErrorFiltroCantidad.setForeground(new java.awt.Color(204, 0, 0));
        mensajeErrorFiltroCantidad.setText(".");
        jPanel3.add(mensajeErrorFiltroCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 350, -1));

        jTabbedPane1.addTab("Inventario Cantidad/Precio", jPanel3);

        tablaPawnVencida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idEmpeño", "Artículo", "Descripción", "PrecioUnitario", "PrecioTotal", "FechaInicial", "FechaLimite", "Empeñador", "Cedula"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaPawnVencida);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Articulos empeñados vencidos", jPanel4);

        tablaReporteVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idProducto", "Fecha de la venta", "Articulo", "Cantidad", "Precio Unitario", "Precio Total", "Comprador", "Cedula Comprador", "Vendedor", "Cedula Vendedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaReporteVenta);

        btnSinFiltro1.setText("Sin Filtro");
        btnSinFiltro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinFiltro1ActionPerformed(evt);
            }
        });

        btnFiltrarFecha1.setText("Filtrar");
        btnFiltrarFecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarFecha1ActionPerformed(evt);
            }
        });

        jLabel4.setText("FechaSuperior");

        jLabel5.setText("FechaInferior");

        mensajeErrorFecha1.setForeground(new java.awt.Color(204, 0, 0));
        mensajeErrorFecha1.setText(".");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnSinFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(437, 437, 437)
                .addComponent(btnFiltrarFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(inputFechaInferio1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(inputFechaSuperior1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(mensajeErrorFecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(inputFechaInferio1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(4, 4, 4)
                                .addComponent(inputFechaSuperior1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFiltrarFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSinFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(mensajeErrorFecha1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Reporte ventas por fecha", jPanel5);

        tablaReportePawn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idEmpeño", "Articulo", "Descripción", "Cantidad", "PrecioUnitario", "PrecioTotal", "FechaLimite", "Empeñador", "CedulaEmpeñador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tablaReportePawn);

        btnSinFiltro2.setText("Sin Filtro");
        btnSinFiltro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinFiltro2ActionPerformed(evt);
            }
        });

        btnFiltrarFecha2.setText("Filtrar");
        btnFiltrarFecha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarFecha2ActionPerformed(evt);
            }
        });

        jLabel6.setText("FechaInferior");

        jLabel7.setText("FechaSuperior");

        mensajeErrorFecha2.setForeground(new java.awt.Color(204, 0, 0));
        mensajeErrorFecha2.setText(".");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnSinFiltro2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 413, Short.MAX_VALUE)
                        .addComponent(btnFiltrarFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(inputFechaInferio2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(inputFechaSuperior2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(mensajeErrorFecha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSinFiltro2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFiltrarFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(inputFechaInferio2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(4, 4, 4)
                                .addComponent(inputFechaSuperior2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addComponent(mensajeErrorFecha2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reporte empeño por fecha", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoOrdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoOrdButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoOrdButtonActionPerformed

    private void OrdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdButtonActionPerformed

    private void btnAceptarFiltroCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarFiltroCantidadActionPerformed

        String CantSearch = inputCantSearch.getText();
        String valorMinimo = inputValorMinSearch.getText();
        String valorMaximo = inputValorMaxSearch.getText();
        mensajeErrorFiltroCantidad.setText("");

        if (OrdButton.isSelected()) {
            if (validacionesFiltroRango()) {
                LecturaEscritura.actualizarTablaRange("listadoArticulo.csv", InvCantidadPrecio, TablaProd, CantSearch, valorMinimo, valorMaximo);
            }
        }

        if (NoOrdButton.isSelected()) {
            LecturaEscritura.actualizarTabla("listadoArticulo.csv", InvCantidadPrecio, TablaProd);
        }
    }//GEN-LAST:event_btnAceptarFiltroCantidadActionPerformed

    private void btnCerraSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerraSesionActionPerformed
        LoginPage loginPage = new LoginPage();
        this.setVisible(false);
        loginPage.setVisible(true);
    }//GEN-LAST:event_btnCerraSesionActionPerformed

    private void btnActualizarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUsuariosActionPerformed
        LecturaEscritura.actualizarTabla("usuarios.csv", ListaUser, TablaUser);
    }//GEN-LAST:event_btnActualizarUsuariosActionPerformed

    private void btnAbrirModalEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirModalEditarActionPerformed
        Access=true;
        EditarUser EditPopup = new EditarUser();
        EditPopup.setVisible(true);
    }//GEN-LAST:event_btnAbrirModalEditarActionPerformed

    private void btnFiltrarFecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarFecha1ActionPerformed
        if (validacionesFecha1()) {
            try {
                LecturaEscritura.filtrarEntreFechas("listadoDeCompra.csv", RepVentPorFecha, tablaReporteVenta, inputFechaInferio1.getText().trim(), inputFechaSuperior1.getText().trim(), 1);
            } catch (ParseException ex) {
                Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnFiltrarFecha1ActionPerformed

    private void btnSinFiltro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinFiltro1ActionPerformed
        LecturaEscritura.actualizarTabla("listadoDeCompra.csv", RepVentPorFecha, tablaReporteVenta);
    }//GEN-LAST:event_btnSinFiltro1ActionPerformed

    private void btnFiltrarFecha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarFecha2ActionPerformed
        if (validacionesFecha2()) {
            try {
                LecturaEscritura.filtrarEntreFechas("listadoEmpeñado.csv", RepEmpPorFecha, tablaReportePawn, inputFechaInferio2.getText().trim(), inputFechaSuperior2.getText().trim(), 6);
            } catch (ParseException ex) {
                Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnFiltrarFecha2ActionPerformed

    private void btnSinFiltro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinFiltro2ActionPerformed
        LecturaEscritura.actualizarTabla("listadoEmpeñado.csv", RepEmpPorFecha, tablaReportePawn);
    }//GEN-LAST:event_btnSinFiltro2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CrearUsuarioAdmin modal = new CrearUsuarioAdmin();
        modal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean validacionesFecha2() {
        mensajeErrorFecha2.setText("");

        if (inputFechaInferio2.getText().trim().length() <= 0 && inputFechaSuperior2.getText().trim().length() <= 0) {
            mensajeErrorFecha2.setText("Se requieren 2 fechas");
            return false;
        }

        try {
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
            formatoFecha.setLenient(false);
            formatoFecha.parse(inputFechaSuperior2.getText());
            formatoFecha.parse(inputFechaInferio2.getText());
        } catch (ParseException e) {
            mensajeErrorFecha2.setText("la fecha ingresada no es una fecha valida");
            return false;
        }

        mensajeErrorFecha2.setText("");

        return true;
    }

    public boolean validacionesFecha1() {
        mensajeErrorFecha1.setText("");

        if (inputFechaInferio1.getText().trim().length() <= 0 && inputFechaSuperior1.getText().trim().length() <= 0) {
            mensajeErrorFecha1.setText("Se requieren 2 fechas");
            return false;
        }

        try {
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
            formatoFecha.setLenient(false);
            formatoFecha.parse(inputFechaSuperior1.getText());
            formatoFecha.parse(inputFechaInferio1.getText());
        } catch (ParseException e) {
            mensajeErrorFecha1.setText("la fecha ingresada no es una fecha valida");
            return false;
        }

        mensajeErrorFecha1.setText("");

        return true;
    }

    public boolean validacionesFiltroRango() {
        mensajeErrorFiltroCantidad.setText("");

        if (inputValorMaxSearch.getText().trim().length() <= 0) {
            mensajeErrorFiltroCantidad.setText("Se requiere un valor maximo");
            return false;
        }

        if (!inputValorMaxSearch.getText().trim().matches("^([0-9])*$")) {
            mensajeErrorFiltroCantidad.setText("Solamente se permite numeros");
            return false;
        }

        if (inputValorMinSearch.getText().trim().length() <= 0) {
            mensajeErrorFiltroCantidad.setText("Se requiere un valor minimo");
            return false;
        }

        if (!inputValorMinSearch.getText().trim().matches("^([0-9])*$")) {
            mensajeErrorFiltroCantidad.setText("Solamente se permite numeros");
            return false;
        }

        if (!inputCantSearch.getText().trim().matches("^([0-9])*$")) {
            mensajeErrorFiltroCantidad.setText("Solamente se permite numeros");
            return false;
        }

        mensajeErrorFiltroCantidad.setText("");

        return true;

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Encabezado;
    private javax.swing.ButtonGroup GroupButton;
    private javax.swing.JRadioButton NoOrdButton;
    private javax.swing.JRadioButton OrdButton;
    private javax.swing.JTable TablaProd;
    private javax.swing.JTable TablaUser;
    private javax.swing.JButton btnAbrirModalEditar;
    private javax.swing.JButton btnAceptarFiltroCantidad;
    private javax.swing.JButton btnActualizarUsuarios;
    private javax.swing.JButton btnCerraSesion;
    private javax.swing.JButton btnFiltrarFecha1;
    private javax.swing.JButton btnFiltrarFecha2;
    private javax.swing.JButton btnSinFiltro1;
    private javax.swing.JButton btnSinFiltro2;
    private javax.swing.JTextField inputCantSearch;
    private javax.swing.JTextField inputFechaInferio1;
    private javax.swing.JTextField inputFechaInferio2;
    private javax.swing.JTextField inputFechaSuperior1;
    private javax.swing.JTextField inputFechaSuperior2;
    private javax.swing.JTextField inputValorMaxSearch;
    private javax.swing.JTextField inputValorMinSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mensajeErrorFecha1;
    private javax.swing.JLabel mensajeErrorFecha2;
    private javax.swing.JLabel mensajeErrorFiltroCantidad;
    private javax.swing.JTable tablaPawnVencida;
    private javax.swing.JTable tablaReportePawn;
    private javax.swing.JTable tablaReporteVenta;
    // End of variables declaration//GEN-END:variables
}
