/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author juandiaz
 */
public class CrearUsuarioAdmin extends javax.swing.JFrame {

    /**
     * Creates new form CrearUsuarioAdmin
     */
    public CrearUsuarioAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputPrimerNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputPrimerApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputCedula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();
        inputRepetirPassword = new javax.swing.JPasswordField();
        jlabel9 = new javax.swing.JLabel();
        inputSegundoApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputSegundoNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        isAdmin = new javax.swing.JRadioButton();
        mensajeError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PANEL AGREGAR USUARIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel2.setText("Primer Nombre:");

        inputPrimerNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPrimerNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Primer Apellido:");

        inputPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPrimerApellidoActionPerformed(evt);
            }
        });

        jLabel5.setText("Cedula:");

        inputCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCedulaActionPerformed(evt);
            }
        });

        jLabel7.setText("Contraseña:");

        btnSubmit.setBackground(new java.awt.Color(204, 255, 204));
        btnSubmit.setText("Enviar");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jlabel9.setText("Repetir Contraseña: ");

        inputSegundoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSegundoApellidoActionPerformed(evt);
            }
        });

        jLabel4.setText("Segundo Apellido: ");

        inputSegundoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSegundoNombreActionPerformed(evt);
            }
        });

        jLabel6.setText("Segundo Nombre: ");

        isAdmin.setText("Es Admin?");
        isAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isAdminActionPerformed(evt);
            }
        });

        mensajeError.setForeground(new java.awt.Color(204, 0, 0));
        mensajeError.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(inputPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(inputSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(inputPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(inputSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(inputCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(isAdmin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7)
                        .addGap(83, 83, 83)
                        .addComponent(jlabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(inputRepetirPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(mensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(isAdmin)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jlabel9))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputRepetirPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(mensajeError)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputPrimerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPrimerNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPrimerNombreActionPerformed

    private void inputPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPrimerApellidoActionPerformed

    private void inputCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCedulaActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        if (validarDatos(inputCedula.getText().trim())) {
            // Colocar Null en caso de no tener segundo nombre o apellido
            String segundoNombre = ".";
            String segundoApellido = ".";
            if (inputSegundoNombre.getText().trim().length() > 0) {
                segundoNombre = inputSegundoNombre.getText();
            }
            if (inputSegundoApellido.getText().trim().length() > 0) {
                segundoApellido = inputSegundoApellido.getText();
            }

            //guarda los datos en "usuarios.csv"
            String datos = inputPrimerNombre.getText().trim() + ";" + segundoNombre + ";" + inputPrimerApellido.getText().trim() + ";" + segundoApellido + ";" + inputCedula.getText().trim() + ";" + inputPassword.getText().trim() + ";" + isAdmin.isSelected() + "\n";
            LecturaEscritura.RegistrarDato("usuarios.csv", datos);

            //lipia los datos
            limpiarFormulario();
            this.setVisible(false);
            mensajeError.setText("");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    //valida que todos los datos que se introduzca en el formulario estén bien
    public boolean validarDatos(String cedula) {

        //verifica cada datos debe tener por lo menos 2 caracteres y sin espacios en blanco al inicio y final
        if (inputPrimerNombre.getText().trim().length() < 2) {
            mensajeError.setText("El primer nombre debe contener mas de 2 letras");
            return false;
        }

        if (inputPrimerApellido.getText().trim().length() < 2) {
            mensajeError.setText("El primer apellido debe contener mas de 2 letras");
            return false;
        }

        if (inputCedula.getText().trim().length() <= 0) {
            mensajeError.setText("Se requiere una cedula");
            return false;
        }

        if (isRegistrado(cedula)) {
            mensajeError.setText("La cedula ya se encuentra registrada");
            return false;
        }

        if (!inputCedula.getText().trim().matches("^([0-9])*$")) {
            mensajeError.setText("Solamente se permite numero en la cedula");
            return false;
        }

        if (inputPassword.getText().trim().length() == 0) {
            mensajeError.setText("Debe ingresar una contraseña");
            return false;
        }

        if (!inputPassword.getText().trim().equals(inputRepetirPassword.getText().trim())) {
            mensajeError.setText("Las contraseñas ingresadas son diferentes");
            return false;
        }

        mensajeError.setText("");
        return true;
    }

    //limpia los datos del formulario una vez registrado
    public void limpiarFormulario() {
        inputCedula.setText("");
        inputPassword.setText("");
        inputPrimerApellido.setText("");
        inputPrimerNombre.setText("");
        inputRepetirPassword.setText("");
        inputSegundoApellido.setText("");
        inputSegundoNombre.setText("");
    }
    
      //busca si ya se encuentra registrado la cedula
    public boolean isRegistrado(String cedula) {
        File ruta = new File("usuarios.csv");
        FileReader lector;
        try {
            lector = new FileReader(ruta);
            BufferedReader bf = new BufferedReader(lector);
            String linea = bf.readLine();
            String[] datosPorPartes;
            while (linea != null) {
                datosPorPartes = linea.split(";");
                //verifica si se encuentra registrado la cedula
                if (datosPorPartes[4].equals(cedula)) {
                    return true;
                }

                linea = bf.readLine();
            }
            lector.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }


    private void inputSegundoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSegundoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSegundoApellidoActionPerformed

    private void inputSegundoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSegundoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSegundoNombreActionPerformed

    private void isAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuarioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuarioAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextField inputCedula;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputPrimerApellido;
    private javax.swing.JTextField inputPrimerNombre;
    private javax.swing.JPasswordField inputRepetirPassword;
    private javax.swing.JTextField inputSegundoApellido;
    private javax.swing.JTextField inputSegundoNombre;
    private javax.swing.JRadioButton isAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabel9;
    private javax.swing.JLabel mensajeError;
    // End of variables declaration//GEN-END:variables
}
