/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author juandiaz
 */
public class LoginPage extends javax.swing.JFrame {

    static String[] datoDeIngreso;

    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectLoginPage = new javax.swing.JTabbedPane();
        panelInciarSesión = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        inputLoginCedula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputLoginPassword = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        mensajeErrorIniciarSesion = new javax.swing.JLabel();
        mensajeERRORIniciar = new javax.swing.JLabel();
        panelRegistrarse = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputPrimerNombre = new javax.swing.JTextField();
        inputSegundoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputPrimerApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputSegundoApellido = new javax.swing.JTextField();
        inputCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlabel9 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        mensajeError = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        inputRepetirPassword = new javax.swing.JPasswordField();
        mensajeExito = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Ingrese su cedula");

        inputLoginCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLoginCedulaActionPerformed(evt);
            }
        });

        jLabel8.setText("Ingrese su contraseña");

        btnIniciarSesion.setBackground(new java.awt.Color(204, 255, 204));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        mensajeErrorIniciarSesion.setForeground(new java.awt.Color(204, 0, 0));

        mensajeERRORIniciar.setForeground(new java.awt.Color(204, 0, 0));
        mensajeERRORIniciar.setText(".");

        javax.swing.GroupLayout panelInciarSesiónLayout = new javax.swing.GroupLayout(panelInciarSesión);
        panelInciarSesión.setLayout(panelInciarSesiónLayout);
        panelInciarSesiónLayout.setHorizontalGroup(
            panelInciarSesiónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInciarSesiónLayout.createSequentialGroup()
                .addGroup(panelInciarSesiónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInciarSesiónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(inputLoginCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelInciarSesiónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInciarSesiónLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel6))
                            .addGroup(panelInciarSesiónLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(panelInciarSesiónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelInciarSesiónLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel8))
                                    .addComponent(inputLoginPassword)
                                    .addComponent(btnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))))
                    .addGroup(panelInciarSesiónLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(mensajeERRORIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mensajeErrorIniciarSesion)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelInciarSesiónLayout.setVerticalGroup(
            panelInciarSesiónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInciarSesiónLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputLoginCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mensajeErrorIniciarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensajeERRORIniciar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        selectLoginPage.addTab("Iniciar Sesión", panelInciarSesión);

        jLabel1.setText("Primer Nombre:");

        inputPrimerNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPrimerNombreActionPerformed(evt);
            }
        });

        inputSegundoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSegundoNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Segundo Nombre: ");

        inputPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPrimerApellidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Primer Apellido:");

        jLabel4.setText("Segundo Apellido: ");

        inputSegundoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSegundoApellidoActionPerformed(evt);
            }
        });

        inputCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCedulaActionPerformed(evt);
            }
        });

        jLabel5.setText("Cedula:");

        jLabel7.setText("Contraseña:");

        jlabel9.setText("Repetir Contraseña: ");

        btnSubmit.setBackground(new java.awt.Color(204, 255, 204));
        btnSubmit.setText("Enviar");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        mensajeError.setForeground(new java.awt.Color(204, 0, 51));

        mensajeExito.setForeground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout panelRegistrarseLayout = new javax.swing.GroupLayout(panelRegistrarse);
        panelRegistrarse.setLayout(panelRegistrarseLayout);
        panelRegistrarseLayout.setHorizontalGroup(
            panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarseLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrarseLayout.createSequentialGroup()
                        .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inputPassword)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputPrimerNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputPrimerApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabel9)
                            .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(inputSegundoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(inputSegundoApellido))
                            .addComponent(inputRepetirPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(panelRegistrarseLayout.createSequentialGroup()
                        .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRegistrarseLayout.createSequentialGroup()
                                .addComponent(mensajeExito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mensajeError))
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelRegistrarseLayout.setVerticalGroup(
            panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarseLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRegistrarseLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistrarseLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRegistrarseLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistrarseLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel9)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputRepetirPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mensajeExito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensajeError)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        selectLoginPage.addTab("Registrarse", panelRegistrarse);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel9.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("TUMERCADO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(selectLoginPage, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(selectLoginPage, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputPrimerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPrimerNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPrimerNombreActionPerformed

    private void inputSegundoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSegundoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSegundoNombreActionPerformed

    private void inputPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPrimerApellidoActionPerformed

    private void inputSegundoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSegundoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSegundoApellidoActionPerformed

    private void inputCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCedulaActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed


        if (validarDatos(inputCedula.getText().trim())) {
            // Colocar Null en caso de no tener segundo nombre o apellido 
            String segundoNombre = ".";
            String segundoApellido = ".";
            if (inputSegundoNombre.getText().trim().length() > 0) {
                segundoNombre = inputSegundoNombre.getText();
            }
            if (inputSegundoApellido.getText().trim().length() > 0) {
                segundoApellido = inputSegundoApellido.getText();
            }

            //guarda los datos en "usuarios.csv"
            String datos = inputPrimerNombre.getText().trim() + ";" + segundoNombre + ";" + inputPrimerApellido.getText().trim() + ";" + segundoApellido + ";" + inputCedula.getText().trim() + ";" + inputPassword.getText().trim() + ";" + "false" + "\n";
            LecturaEscritura.RegistrarDato("usuarios.csv", datos);

            //limpia los datos
            limpiarFormulario();
            mensajeExito.setText("Se ha registrado correctamente!");

        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        File ruta = new File("usuarios.csv");
        FileReader lector;
        try {
            lector = new FileReader(ruta);
            BufferedReader bf = new BufferedReader(lector);
            String linea = bf.readLine();
            String[] datosPorPartes;
            while (linea != null) {
                datosPorPartes = linea.split(";");
                //verifica si se encuentra registrado la cedula
                if (datosPorPartes[4].equals(inputLoginCedula.getText())) {
                    //verifica si la contraseña son iguales              
                    if (datosPorPartes[5].equals(inputLoginPassword.getText())) {
                        //registramos los datos de quien ingresó para utilizarlo en la otra ventana
                        datoDeIngreso = datosPorPartes;
                        //lo envia al panel correspondiente
                        boolean isAdmin = Boolean.parseBoolean(datosPorPartes[6]);
                        cambiarVentana(isAdmin);
                    }
                }

                linea = bf.readLine();
            }
            lector.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void inputLoginCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLoginCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLoginCedulaActionPerformed

    //nos cambia de ventana hacia el panelAdministrado o Usuario
    public void cambiarVentana(boolean isAdmin) {
        if (isAdmin) {
            AdminPanel adminPanel = new AdminPanel();
            this.setVisible(false);
            //adminPanel.setExtendedState(JFrame.MAXIMIZED_BOTH);
            adminPanel.setVisible(true);
        } else {
            UsuarioPanel usuarioPanel = new UsuarioPanel();
            this.setVisible(false);
            //usuarioPanel.setExtendedState(JFrame.MAXIMIZED_BOTH);
            usuarioPanel.setVisible(true);
        }
    }

    //valida que todos los datos que se introduzca en el formulario estén bien
    public boolean validarDatos(String cedula) {

        //verifica cada datos debe tener por lo menos 2 caracteres y sin espacios en blanco al inicio y final
        if (inputPrimerNombre.getText().trim().length() < 2) {
            mensajeError.setText("El primer nombre debe contener mas de 2 letras");
            return false;
        }

        if (inputPrimerApellido.getText().trim().length() < 2) {
            mensajeError.setText("El primer apellido debe contener mas de 2 letras");
            return false;
        }
        
        if(!SoloLet(inputPrimerNombre.getText().trim(),inputPrimerApellido.getText().trim())){
            mensajeError.setText("El nombre y el apellido deben solo contener letras");
            return false;
        }

        if (inputCedula.getText().trim().length() <= 0) {
            mensajeError.setText("Se requiere una cedula");
            return false;
        }

        if (isRegistrado(cedula)) {
            mensajeError.setText("La cedula ya se encuentra registrada");
            return false;
        }

        if (!inputCedula.getText().trim().matches("^([0-9])*$")) {
            mensajeError.setText("Solamente se permite numero en la cedula");
            return false;
        }

        if (inputPassword.getText().trim().length() == 0) {
            mensajeError.setText("Debe ingresar una contraseña");
            return false;
        }

        if (!inputPassword.getText().trim().equals(inputRepetirPassword.getText().trim())) {
            mensajeError.setText("Las contraseñas ingresadas son diferentes");
            return false;
        }

        mensajeError.setText("");
        return true;
    }
    
    public Boolean SoloLet(String Exp1, String Exp2){
        return Exp1.matches("^[a-zA-Z]*$")&&Exp2.matches("^[a-zA-Z]*$");
    }

    //limpia los datos del formulario una vez registrado
    public void limpiarFormulario() {
        inputCedula.setText("");
        inputLoginCedula.setText("");
        inputLoginPassword.setText("");
        inputPassword.setText("");
        inputPrimerApellido.setText("");
        inputPrimerNombre.setText("");
        inputRepetirPassword.setText("");
        inputSegundoApellido.setText("");
        inputSegundoNombre.setText("");
        mensajeError.setText("");
    }

    //busca si ya se encuentra registrado la cedula
    public boolean isRegistrado(String cedula) {
        File ruta = new File("usuarios.csv");
        FileReader lector;
        try {
            lector = new FileReader(ruta);
            BufferedReader bf = new BufferedReader(lector);
            String linea = bf.readLine();
            String[] datosPorPartes;
            while (linea != null) {
                datosPorPartes = linea.split(";");
                //verifica si se encuentra registrado la cedula
                if (datosPorPartes[4].equals(cedula)) {
                    return true;
                }

                linea = bf.readLine();
            }
            lector.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextField inputCedula;
    private javax.swing.JTextField inputLoginCedula;
    private javax.swing.JPasswordField inputLoginPassword;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputPrimerApellido;
    private javax.swing.JTextField inputPrimerNombre;
    private javax.swing.JPasswordField inputRepetirPassword;
    private javax.swing.JTextField inputSegundoApellido;
    private javax.swing.JTextField inputSegundoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabel9;
    private javax.swing.JLabel mensajeERRORIniciar;
    private javax.swing.JLabel mensajeError;
    private javax.swing.JLabel mensajeErrorIniciarSesion;
    private javax.swing.JLabel mensajeExito;
    private javax.swing.JPanel panelInciarSesión;
    private javax.swing.JPanel panelRegistrarse;
    private javax.swing.JTabbedPane selectLoginPage;
    // End of variables declaration//GEN-END:variables
}
