/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author juandiaz
 */
public class ModalNewPawn extends javax.swing.JFrame {

    /**
     * Creates new form ModalNewPawn
     */
    public ModalNewPawn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPawnFinalizar = new javax.swing.JButton();
        btnPawnCancelar = new javax.swing.JButton();
        inputPawnDescripcion = new javax.swing.JTextField();
        inputPawnCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputPawnValor = new javax.swing.JTextField();
        inputPawnTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputPawnFechaVencimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mensajeERROR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("PANEL DE EMPEÑO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnPawnFinalizar.setText("Empeñar");
        btnPawnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPawnFinalizarActionPerformed(evt);
            }
        });

        btnPawnCancelar.setText("Cancelar");
        btnPawnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPawnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Descripción: ");

        jLabel5.setText("Cantidad");

        jLabel2.setText("Artículo");

        jLabel4.setText("Precio Unitario");

        inputPawnFechaVencimiento.setText("dd/mm/aaaa");
        inputPawnFechaVencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPawnFechaVencimientoActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha de vencimiento");

        mensajeERROR.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputPawnFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnPawnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPawnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(mensajeERROR)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputPawnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(inputPawnDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputPawnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(inputPawnValor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPawnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPawnValor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPawnDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPawnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPawnFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPawnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPawnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mensajeERROR)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPawnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPawnFinalizarActionPerformed
        if (validacion()) {
            //los datos del producto a empeñar en formato csv
            Date fecha = new Date();
            //Se le suma el año actual por ser cosa del metodo
            int year = fecha.getYear() + 1900;
            String fechaFormateada = fecha.getDate() + "/" + fecha.getMonth() + "/" + year;
            String datos = generadorDeCodigo() + ";" + inputPawnTitulo.getText() + ";" + inputPawnDescripcion.getText() + ";" + inputPawnCantidad.getText() + ";" + inputPawnValor.getText() + ";" + Integer.parseInt(inputPawnValor.getText()) * Integer.parseInt(inputPawnCantidad.getText()) + ";" + fechaFormateada + ";" + inputPawnFechaVencimiento.getText() + ";" + LoginPage.datoDeIngreso[0] + ";" + LoginPage.datoDeIngreso[4] + "\n";
            LecturaEscritura.RegistrarDato("listadoEmpeñado.csv", datos);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnPawnFinalizarActionPerformed

    private void btnPawnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPawnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnPawnCancelarActionPerformed

    private void inputPawnFechaVencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPawnFechaVencimientoActionPerformed

    }//GEN-LAST:event_inputPawnFechaVencimientoActionPerformed

    public boolean validacion() {

        mensajeERROR.setText("");

        if (inputPawnTitulo.getText().trim().length() < 2) {
            mensajeERROR.setText("El Artículo debe tener mas de 2 letras");
            return false;
        }

        if (inputPawnDescripcion.getText().trim().length() < 5) {
            mensajeERROR.setText("la descripción debe tener mas de 5 letras");
            return false;
        }

        if (inputPawnValor.getText().trim().length() <= 0) {
            mensajeERROR.setText("Se requiere un precio unitario");
            return false;
        }

        if (!inputPawnValor.getText().trim().matches("^([0-9])*$")) {
            mensajeERROR.setText("el precio debe contener unicamente numeros");
            return false;
        }

        if (inputPawnCantidad.getText().trim().length() <= 0) {
            mensajeERROR.setText("Se requiere una cantidad");
            return false;
        }

        if (!inputPawnCantidad.getText().trim().matches("^([0-9])*$")) {
            mensajeERROR.setText("la cantidad debe contener unicamente numeros");
            return false;
        }

        try {
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
            formatoFecha.setLenient(false);
            formatoFecha.parse(inputPawnFechaVencimiento.getText());
        } catch (ParseException e) {
            mensajeERROR.setText("la fecha ingresada no es una fecha valida");
            return false;
        }

        try {
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
            Date fechaDate = formatoFecha.parse(inputPawnFechaVencimiento.getText());
            if (fechaDate.before(new Date())) {
                mensajeERROR.setText("Se debe ingresar una fecha superior a la actual");
                return false;
            }
        } catch (ParseException e) {
            System.out.println("Error: " + e.getMessage());
        }

        return true;

    }

    public String generadorDeCodigo() {
        int numero = (int) (Math.random() * (9000 - 1000) + 1000);
        return String.valueOf(numero);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalNewPawn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalNewPawn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalNewPawn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalNewPawn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModalNewPawn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPanelVentaCancelar;
    private javax.swing.JButton btnPanelVentaCancelar1;
    private javax.swing.JButton btnPawnCancelar;
    private javax.swing.JButton btnPawnFinalizar;
    private javax.swing.JTextField inputPawnCantidad;
    private javax.swing.JTextField inputPawnDescripcion;
    private javax.swing.JTextField inputPawnFechaVencimiento;
    private javax.swing.JTextField inputPawnTitulo;
    private javax.swing.JTextField inputPawnValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mensajeERROR;
    // End of variables declaration//GEN-END:variables
}
