/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juandiaz
 */
public class UsuarioPanel extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioPanel
     */
    public DefaultTableModel DatostablaArticulo;
    public DefaultTableModel DatostablaHistorialCompras;
    public DefaultTableModel DatostablaHistorialVentas;
    public DefaultTableModel DatostablaListadoPawn;

    public UsuarioPanel() {
        initComponents();
        titulo.setText("Bienvenido a tu mercado, " + LoginPage.datoDeIngreso[0]);

        //esto actualiza las ventas de los empeños
        LecturaEscritura.ActualizarPawns("listadoEmpeñado.csv");

        //INICIALIZA LA TABLA DE LOS ARTICULOS-------
        DatostablaArticulo = new DefaultTableModel();
        DatostablaArticulo.addColumn("Codigo");
        DatostablaArticulo.addColumn("Artículo");
        DatostablaArticulo.addColumn("Descripción");
        DatostablaArticulo.addColumn("Precio");
        DatostablaArticulo.addColumn("Cantidad");
        DatostablaArticulo.addColumn("Vendedor");
        DatostablaArticulo.addColumn("CedulaVendedor");
        LecturaEscritura.actualizarTabla("listadoArticulo.csv", DatostablaArticulo, TablaArticulos);

        //INICIALIZA LA TABLA HISTORIAL DE COMPRA-------
        DatostablaHistorialCompras = new DefaultTableModel();
        DatostablaHistorialCompras.addColumn("idCompra");
        DatostablaHistorialCompras.addColumn("Fecha");
        DatostablaHistorialCompras.addColumn("Artículo");
        DatostablaHistorialCompras.addColumn("Cantidad");
        DatostablaHistorialCompras.addColumn("PrecioUnitario");
        DatostablaHistorialCompras.addColumn("PrecioTotal");
        DatostablaHistorialCompras.addColumn("Comprador");
        DatostablaHistorialCompras.addColumn("CedulaComprador");
        DatostablaHistorialCompras.addColumn("Vendedor");
        DatostablaHistorialCompras.addColumn("CedulaVendedor");
        LecturaEscritura.actualizarTablaFiltradoCedula("listadoDeCompra.csv", DatostablaHistorialCompras, TablaHistorialCompra, 7, 4);

        //INICIALIZA LA TABLA HISTORIAL DE VENTA-------
        DatostablaHistorialVentas = new DefaultTableModel();
        DatostablaHistorialVentas.addColumn("idVenta");
        DatostablaHistorialVentas.addColumn("Fecha");
        DatostablaHistorialVentas.addColumn("Artículo");
        DatostablaHistorialVentas.addColumn("Cantidad");
        DatostablaHistorialVentas.addColumn("PrecioUnitario");
        DatostablaHistorialVentas.addColumn("PrecioTotal");
        DatostablaHistorialVentas.addColumn("Comprador");
        DatostablaHistorialVentas.addColumn("CedulaComprador");
        DatostablaHistorialVentas.addColumn("Vendedor");
        DatostablaHistorialVentas.addColumn("CedulaVendedor");
        LecturaEscritura.actualizarTablaFiltradoCedula("listadoDeCompra.csv", DatostablaHistorialVentas, TablaHistorialVenta, 9, 4);

        //INICIALIZA LA TABLA EMPEÑOS-------
        DatostablaListadoPawn = new DefaultTableModel();
        DatostablaListadoPawn.addColumn("idEmpeño");
        DatostablaListadoPawn.addColumn("Artículo");
        DatostablaListadoPawn.addColumn("Descripción");
        DatostablaListadoPawn.addColumn("Cantidad");
        DatostablaListadoPawn.addColumn("PrecioUnitario");
        DatostablaListadoPawn.addColumn("PrecioTotal");
        DatostablaListadoPawn.addColumn("FechaInicial");
        DatostablaListadoPawn.addColumn("FechaLimite");
        DatostablaListadoPawn.addColumn("Empeñador");
        DatostablaListadoPawn.addColumn("Cedula");
        LecturaEscritura.actualizarTablaFiltradoCedula("listadoEmpeñado.csv", DatostablaListadoPawn, TablaListadoPawn, 9, 4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaArticulos = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnPublicarArticulo = new javax.swing.JToggleButton();
        btnComprarArticulo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaHistorialCompra = new javax.swing.JTable();
        btnActualizarHistorialCompra = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaListadoPawn = new javax.swing.JTable();
        btnPawnActualizar = new javax.swing.JButton();
        btnNewPawn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaHistorialVenta = new javax.swing.JTable();
        btnActualizarHistorialVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        titulo.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(102, 102, 102));
        titulo.setText("Bienvenido a tu mercado, ");

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        EditButton.setText("EditarInfo");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
            .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Artículo", "Descripción", "Precio", "cantidad", "vendedor", "cedulaVendedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaArticulos);
        if (TablaArticulos.getColumnModel().getColumnCount() > 0) {
            TablaArticulos.getColumnModel().getColumn(0).setResizable(false);
            TablaArticulos.getColumnModel().getColumn(1).setResizable(false);
            TablaArticulos.getColumnModel().getColumn(2).setResizable(false);
            TablaArticulos.getColumnModel().getColumn(3).setResizable(false);
            TablaArticulos.getColumnModel().getColumn(4).setResizable(false);
            TablaArticulos.getColumnModel().getColumn(5).setResizable(false);
            TablaArticulos.getColumnModel().getColumn(6).setResizable(false);
        }

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnPublicarArticulo.setText("Publicar un articulo");
        btnPublicarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicarArticuloActionPerformed(evt);
            }
        });

        btnComprarArticulo.setText("Comprar Articulo");
        btnComprarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarArticuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComprarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPublicarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPublicarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Todo los articulos", jPanel2);

        TablaHistorialCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idCompra", "Fecha", "Articulo", "Cantidad", "PrecioUnitario", "PrecioTotal", "Comprador", "CedulaUsuarioComprador", "Vendedor", "CedulaVendedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaHistorialCompra);
        if (TablaHistorialCompra.getColumnModel().getColumnCount() > 0) {
            TablaHistorialCompra.getColumnModel().getColumn(0).setResizable(false);
            TablaHistorialCompra.getColumnModel().getColumn(1).setResizable(false);
            TablaHistorialCompra.getColumnModel().getColumn(2).setResizable(false);
            TablaHistorialCompra.getColumnModel().getColumn(3).setResizable(false);
            TablaHistorialCompra.getColumnModel().getColumn(4).setResizable(false);
            TablaHistorialCompra.getColumnModel().getColumn(5).setResizable(false);
            TablaHistorialCompra.getColumnModel().getColumn(6).setResizable(false);
            TablaHistorialCompra.getColumnModel().getColumn(7).setResizable(false);
            TablaHistorialCompra.getColumnModel().getColumn(8).setResizable(false);
            TablaHistorialCompra.getColumnModel().getColumn(9).setResizable(false);
        }

        btnActualizarHistorialCompra.setText("Actualizar");
        btnActualizarHistorialCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarHistorialCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnActualizarHistorialCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addGap(0, 0, 0)
                .addComponent(btnActualizarHistorialCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Historia de compra", jPanel3);

        TablaListadoPawn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idEmpeño", "Articulo", "Descripción", "Cantidad", "PrecioUnitario", "PrecioTotal", "FechaInicial", "FechaLimite", "Empeñador", "Cedula"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TablaListadoPawn);
        if (TablaListadoPawn.getColumnModel().getColumnCount() > 0) {
            TablaListadoPawn.getColumnModel().getColumn(0).setResizable(false);
            TablaListadoPawn.getColumnModel().getColumn(1).setResizable(false);
            TablaListadoPawn.getColumnModel().getColumn(2).setResizable(false);
            TablaListadoPawn.getColumnModel().getColumn(3).setResizable(false);
            TablaListadoPawn.getColumnModel().getColumn(4).setResizable(false);
            TablaListadoPawn.getColumnModel().getColumn(5).setResizable(false);
            TablaListadoPawn.getColumnModel().getColumn(6).setResizable(false);
            TablaListadoPawn.getColumnModel().getColumn(7).setResizable(false);
            TablaListadoPawn.getColumnModel().getColumn(8).setResizable(false);
            TablaListadoPawn.getColumnModel().getColumn(9).setResizable(false);
        }

        btnPawnActualizar.setText("Actualizar");
        btnPawnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPawnActualizarActionPerformed(evt);
            }
        });

        btnNewPawn.setText("Empeñar un artículo");
        btnNewPawn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPawnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnPawnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNewPawn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPawnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewPawn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Listado de empeño", jPanel4);

        TablaHistorialVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idVenta", "Fecha", "Articulo", "Cantidad", "PrecioUnitario", "PrecioTotal", "Comprador", "CedulaComprador", "Vendedor", "CedulaVendedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TablaHistorialVenta);
        if (TablaHistorialVenta.getColumnModel().getColumnCount() > 0) {
            TablaHistorialVenta.getColumnModel().getColumn(0).setResizable(false);
            TablaHistorialVenta.getColumnModel().getColumn(1).setResizable(false);
            TablaHistorialVenta.getColumnModel().getColumn(2).setResizable(false);
            TablaHistorialVenta.getColumnModel().getColumn(3).setResizable(false);
            TablaHistorialVenta.getColumnModel().getColumn(4).setResizable(false);
            TablaHistorialVenta.getColumnModel().getColumn(5).setResizable(false);
            TablaHistorialVenta.getColumnModel().getColumn(6).setResizable(false);
            TablaHistorialVenta.getColumnModel().getColumn(7).setResizable(false);
            TablaHistorialVenta.getColumnModel().getColumn(8).setResizable(false);
            TablaHistorialVenta.getColumnModel().getColumn(9).setResizable(false);
        }

        btnActualizarHistorialVenta.setText("Actualizar");
        btnActualizarHistorialVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarHistorialVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnActualizarHistorialVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnActualizarHistorialVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Historia de venta", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        //cierra el panelcliente y lo envia al login
        LoginPage loginPage = new LoginPage();
        this.setVisible(false);
        loginPage.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        LecturaEscritura.ActualizarPawns("listadoEmpeñado.csv");
        LecturaEscritura.actualizarTabla("listadoArticulo.csv", DatostablaArticulo, TablaArticulos);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnPublicarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicarArticuloActionPerformed
        ModalPublicarArticulo modal = new ModalPublicarArticulo();
        modal.setVisible(true);
    }//GEN-LAST:event_btnPublicarArticuloActionPerformed

    private void btnComprarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarArticuloActionPerformed
        ModalComprarArticulo modal = new ModalComprarArticulo();
        modal.setVisible(true);
    }//GEN-LAST:event_btnComprarArticuloActionPerformed

    private void btnActualizarHistorialCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarHistorialCompraActionPerformed
        LecturaEscritura.ActualizarPawns("listadoEmpeñado.csv");
        LecturaEscritura.actualizarTablaFiltradoCedula("listadoDeCompra.csv", DatostablaHistorialCompras, TablaHistorialCompra, 7, 4);
    }//GEN-LAST:event_btnActualizarHistorialCompraActionPerformed

    private void btnActualizarHistorialVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarHistorialVentaActionPerformed
        LecturaEscritura.ActualizarPawns("listadoEmpeñado.csv");
        LecturaEscritura.actualizarTablaFiltradoCedula("listadoDeCompra.csv", DatostablaHistorialVentas, TablaHistorialVenta, 9, 4);
    }//GEN-LAST:event_btnActualizarHistorialVentaActionPerformed

    private void btnNewPawnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPawnActionPerformed
        ModalNewPawn modal = new ModalNewPawn();
        modal.setVisible(true);
    }//GEN-LAST:event_btnNewPawnActionPerformed

    private void btnPawnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPawnActualizarActionPerformed
        LecturaEscritura.ActualizarPawns("listadoEmpeñado.csv");
        LecturaEscritura.actualizarTabla("listadoArticulo.csv", DatostablaArticulo, TablaArticulos);
        LecturaEscritura.actualizarTablaFiltradoCedula("listadoEmpeñado.csv", DatostablaListadoPawn, TablaListadoPawn, 9, 4);
    }//GEN-LAST:event_btnPawnActualizarActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        EditarUser EditPopup = new EditarUser();
        EditPopup.setVisible(true);
    }//GEN-LAST:event_EditButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioPanel().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditButton;
    private javax.swing.JTable TablaArticulos;
    private javax.swing.JTable TablaHistorialCompra;
    private javax.swing.JTable TablaHistorialVenta;
    private javax.swing.JTable TablaListadoPawn;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizarHistorialCompra;
    private javax.swing.JButton btnActualizarHistorialVenta;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnComprarArticulo;
    private javax.swing.JButton btnNewPawn;
    private javax.swing.JButton btnPawnActualizar;
    private javax.swing.JToggleButton btnPublicarArticulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
